Django11/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('kino/', views.kinolist123.as_view(), name='allkino'),
    #path('kino/<int:id>/<str:title>', views.info, name='info'),
    path('kino/<slug:pk>/<str:title>', views.kinoDetail.as_view(), name='info'),
    path('user/', include('django.contrib.auth.urls')),
    path('actor/', views.Actorlist.as_view(), name='allactors'),
    # path('kino/<int:id>/<str:title>', views.info, name='info'),
    path('actor/<slug:pk>/<str:name>', views.ActorDetail.as_view(), name='infoactor'),
    path('director/', views.Directorlist.as_view(), name='alldirectors'),
    path('director/<slug:pk>/<str:lname>', views.DirectorDetail.as_view(), name='infodirector'),
    path('status/', views.status, name='status'),
    path('status/prosmotr/<int:id1>/<int:id2>/<int:id3>', views.prosmotr, name='prosmotr'),
    path('status/buy/<int:type>/', views.buy, name='buystatus'),
    path('user/registr/', views.registr, name='registr'),


]

catalog/models.py
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    name = models.CharField(max_length=20, verbose_name='Жанр')

    def __str__(self):
        return self.name

class Director(models.Model):
    fname = models.CharField(max_length=20, verbose_name='Имя')
    lname = models.CharField(max_length=20, verbose_name='Фамилия')

    def __str__(self):
        return f'{self.fname}, {self.lname}'

    def get_absolute_url(self):
        return reverse('infodirector', args=[self.id, self.lname])

class Actor(models.Model):
    fname = models.CharField(max_length=20, verbose_name='Имя')
    lname = models.CharField(max_length=20, verbose_name='Фамилия')
    born = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    country = models.CharField(max_length=20, blank=True, null=True, verbose_name='Страна')

    def __str__(self):
        return self.lname

    def get_absolute_url(self):
        return reverse('infoactor', args=[self.id, f'{self.fname} {self.lname}'])

class Status(models.Model):
    VIBOR = (('Бесплатно', 'Бесплатно'), ('Базовая', 'Базовая'), ('Супер', 'Супер'))
    name = models.CharField(max_length=20, choices=VIBOR, verbose_name='Подписка')

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=20, verbose_name='Страна')

    def __str__(self):
        return self.name

class AgeRate(models.Model):
    choise = (('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'))
    rate = models.CharField(max_length=20, choices=choise, verbose_name='Рейтинг')

    def __str__(self):
        return self.rate

class Kino(models.Model):
    title = models.CharField(max_length=20, verbose_name='Название')
    genre = models.ForeignKey(Genre, on_delete=models.SET_DEFAULT, default=1)
    rating = models.FloatField(verbose_name='Оценка')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=500,verbose_name='Описание')
    year = models.IntegerField(verbose_name='год')
    ager = models.ForeignKey(AgeRate, on_delete=models.SET_NULL, null=True)
    actor = models.ManyToManyField(Actor, verbose_name='Актеры')
    status = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=1)
    image = models.CharField(max_length=100, blank=True, null=True, verbose_name='Картинка')

    def __str__(self):
        return self.title

    def display_actors(self):
        res = []
        for a in self.actor.all():
            res.append(a.lname)
        return ', '.join(res)

    display_actors.short_description = 'Актёры'

    #from django.urls import reverse
    def get_absolute_url(self):
        return reverse('info', args=[self.id, self.title])
        #return f'kino/{self.id}/{self.title}'

catalog/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.models import User,Group

# Create your views here.
def index(req):
    numKino = Kino.objects.all().count()
    numActor = Actor.objects.all().count()
    numFree = Kino.objects.filter(status__kino=1).count()
    if req.user.username:
        username = req.user.first_name
        print(req.user.first_name, '#', req.user.id)
    else:
        username = 'Гость'
        print(req.user.id)
    data = {'k1':numKino,'k2':numActor,'k3':numFree,'username':username}
    #user = User.objects.create_user('user2','user2@mail.ru','useruser')
   # user.first_name = 'Vlad'
    #user.last_name = 'Petrov'
    #user.save()
    return render(req,'index.html',context=data)

#def allkino(req):
#    return render(req,'index.html')
from django.views import generic
class kinolist123(generic.ListView):
    model = Kino
    paginate_by = 2

class kinoDetail(generic.DetailView):
    model = Kino

class Actorlist(generic.ListView):
    model = Actor
    paginate_by = 50


class ActorDetail(generic.DetailView):
    model = Actor


class Directorlist(generic.ListView):
    model = Director
    paginate_by = 50


class DirectorDetail(generic.DetailView):
    model = Director

class DetailUser(generic.DetailView):
    model = User
    template_name = 'registration/user_profile.html'
    extra_context = {'title': 'Профиль'}
    context_object_name = 'user'

class UserView(generic.TemplateView):
    template_name = 'registration/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'user': self.request.user,
            'title': self.request.user.username.title()
        })
        return context

#from django.http import HttpResponse
#def info(req,id):
 #   film = Kino.objects.get(id=id)
 #   return HttpResponse(film.title).

def status(req):
    k1 = Status.objects.all()
    data = {'podpiska':k1}
    return render(req,'podpiska.html',context=data)

def prosmotr(req,id1,id2,id3):
    print(id1,id2,id3)
    mas = ['бесплатно', 'базовая', 'супер']  # kino id2
    mas2 = ['free', 'based', 'super']  # user id3
    status=0
    if id3!=0:
        status = User.objects.get(id=id3)
        print(status)
        status = status.groups.all()
        print(status)
        status = status[0].id
        print(status)
    else:
        if id3==0:
            status=1
    if status>=id2:
        print('ok')
        permission = True
    else:
        print('nelza')
        permission = False
    k1 = Kino.objects.get(id=id1).title
    k2 = Group.objects.get(id=status).name
    k3 = Status.objects.get(id=id2).name
    data = {'kino':k1,'status':k2,'statuskino':k3,'prava':permission}
    return render(req, 'prosmotr.html',data)

def buy(req,type):
    usid = req.user.id
    user123 = User.objects.get(id=usid)
    statusnow = user123.groups.all()[0].id
    grold = Group.objects.get(id=statusnow)
    grold.user_set.remove(user123)
    grnew = Group.objects.get(id=type)
    grnew.user_set.add(user123)
    k1 = grnew.name
    data = {'podpiska':k1}
    return render(req, 'buy.html', data)

from .form import SignUpform
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
def registr(req):
    print(1)
    if req.POST:
        print(2)
        anketa = SignUpform(req.POST)
        if anketa.is_valid():
            print(3)
            anketa.save()
            k1 = anketa.cleaned_data.get('username')
            k2 = anketa.cleaned_data.get('password1')
            k3 = anketa.cleaned_data.get('first_name')
            k4 = anketa.cleaned_data.get('last_name')
            k5 = anketa.cleaned_data.get('email')
            user = authenticate(username=k1, password=k2)
            man = User.objects.get(username=k1)
            man.email=k5
            man.first_name=k3
            man.last_name=k4
            man.save()
            login(req,user)
            group = Group.objects.get(id=1)
            group.user_set.add(man)
            return redirect('home')
    else:
        anketa = SignUpform()
    data = {'regform':anketa}
    return render(req,'registration/registration.html',context=data)

templates/buy.html
{% extends 'index.html' %}
{% block content%}
<h2>Вы купили подписку {{ podpiska }}</h2>
{% endblock %}

templates/catalog/actor_detali.html
{% extends 'index.html' %}
{% block content %}
    <div class="center-list">
        <h3>Имя: {{ actor.fname }}</h3>
        <h3>Фамилия: {{ actor.lname }}</h3>
        <h3>Дата рождения: {{ actor.born }}</h3>
        <h3>Страна: {{ actor.country }}</h3>
        <h3>Играл в:</h3>
        <ul>
            {% for kino in actor.kino_set.all %}
                <li><a href="{{ kino.get_absolute_url }}" class="inline-a">{{ kino }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/catalog/actor_list.html
{% extends 'index.html' %}
{% block content %}
    <div class="center-list">
        <h2>Актёры</h2>
        <ul>
            {% for actor in actor_list %}
                <li>
                    <a href="{{ actor.get_absolute_url }}" class="inline-a">{{ actor.fname }} {{ actor.lname }}</a>
                </li>
            {% endfor %}
        </ul>

    {% if is_paginated %}
            {#    <div>#}
            {##}
            {#        {%if page_obj.has_previous %} {# whether the previous page exists #}
            {#            <a href="?page={{page_obj.previous_page_number}}">Пред</a> {# link to the prev page #}
            {#        {% endif %}#}
            {#        <span>страница {{page_obj.number}} из {{ page_obj.paginator.num_pages }}</span> {# the current page number #}
            {##}
            {#        {%if page_obj.has_next %} {# whether the next page exists #}
            {#            <a href="?page={{page_obj.next_page_number}}">След</a> {# link to the next page #}
            {#        {% endif %}#}
            {##}
            {#    </div>#}
            <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
            </div>
        {% endif %}


    </div>

{% endblock content %}

templates/catalog/director_detali.html
{% extends 'index.html' %}
{% block content %}
    <div class="center-list">
        <h3>Имя: {{ director.fname }}</h3>
        <h3>Фамилия: {{ director.lname }}</h3>
        <h3>Фильмография:</h3>
        <ul>
            {% for kino in director.kino_set.all %}
                <li><a href="{{ kino.get_absolute_url }}" class="inline-a">{{ kino }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/catalog/director_list.html
{% extends 'index.html' %}
{% block content %}
    <div class="center-list">
        <h2>Режиссёры</h2>
        <ul>
            {% for director in director_list %}
                <li>
                    <a href="{{ director.get_absolute_url }}"
                       class="inline-a">{{ director.fname }} {{ director.lname }}</a>
                </li>
            {% endfor %}
        </ul>

    {% if is_paginated %}
            {#    <div>#}
            {##}
            {#        {%if page_obj.has_previous %} {# whether the previous page exists #}
            {#            <a href="?page={{page_obj.previous_page_number}}">Пред</a> {# link to the prev page #}
            {#        {% endif %}#}
            {#        <span>страница {{page_obj.number}} из {{ page_obj.paginator.num_pages }}</span> {# the current page number #}
            {##}
            {#        {%if page_obj.has_next %} {# whether the next page exists #}
            {#            <a href="?page={{page_obj.next_page_number}}">След</a> {# link to the next page #}
            {#        {% endif %}#}
            {##}
            {#    </div>#}
            <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
            </div>
        {% endif %}

    </div>

{% endblock content %}

templates/catalog/kino_detail.html
    {% extends 'index.html' %}
    {% load static %}
{% block content %}
        <h2>Фильм {{ kino.title }}</h2>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/podpiska.css' %}">

    <h2>Описание {{ kino.summary }}</h2>
    <h2>Режиссер {{ kino.director }}</h2>
    <h2>Рейтинг {{ kino.ager }}</h2>
    <h2>Уровень подписки {{ kino.status }}</h2>
    <h2>Актеры:</h2>

    {% for actor in kino.actor.all %}
        <p>{{ actor.fname }} // {{ actor.lname }}</p>
        {% endfor %}

    {% endblock %}

templates/catalog/kino_list.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="center-list">
        <h2>Каталог фильмов</h2>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/podpiska.css' %}">

        <ul>
            {% for kino in kino_list %}
                <li>
                    <a href="{{ kino.get_absolute_url }}" class="inline-a">{{ kino.title }}</a>
                    <p>({{ kino.genre }})</p>
                </li>
            {% endfor %}
        </ul>

        {% if is_paginated %}
            {#    <div>#}
            {##}
            {#        {%if page_obj.has_previous %} {# whether the previous page exists #}
            {#            <a href="?page={{page_obj.previous_page_number}}">Пред</a> {# link to the prev page #}
            {#        {% endif %}#}
            {#        <span>страница {{page_obj.number}} из {{ page_obj.paginator.num_pages }}</span> {# the current page number #}
            {##}
            {#        {%if page_obj.has_next %} {# whether the next page exists #}
            {#            <a href="?page={{page_obj.next_page_number}}">След</a> {# link to the next page #}
            {#        {% endif %}#}
            {##}
            {#    </div>#}
            <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
            </div>
        {% endif %}</div>

{% endblock content %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>Кино</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {%  endblock head %}
</head>
<body class="D">
   {% block menu %}
    <div class="menu">
    <a href="{% url 'home' %}">Главная</a>
        <a href="{% url 'allkino' %}">Фильмы</a>
    <a href="{% url 'allactors' %}">Актёры</a>
    <a href="{% url 'alldirectors' %}">Режиссёры</a>
    <a href="{% url 'status' %}">Подсписка</a>
    {% if not user.username %}
        <a href="{% url 'login' %} ">Авторизация</a>
    {% else %}
        <a href="{% url 'logout' %} ">Выход</a>
    {% endif %}

    </div>

   {% endblock menu %}
   {% block content %}

       <div class="content">
        <h1 class="F">Добро пожаловать на KINOTIME {{ username }}</h1>
        <h2 class="F">ЧИТАЙ ИНФОРМАЦИЮ НИЖЕ </h2>
           <h2>&#128071;&#128071;&#128071;&#128071;&#128071;
           &#128071;&#128071;&#128071;&#128071;&#128071;&#128071;&#128071;
           &#128071;&#128071;&#128071;&#128071;&#128071;
           &#128071;&#128071;&#128071;&#128071;&#128071;&#128071;&#128071;</h2>


        <div class="info">
            <h2>На нашем сайте {{ k1 }} фильма</h2>
            <h2>На нашем сайте {{ k2 }} актера</h2>
            <h2>На нашем сайте {{ k3 }} фильма бесплатно</h2>
        </div>
    </div>
   {% endblock content %}
</body>
</html>

templates/podpiska.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>Все фильмы</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/podpiska.css' %}">
    {%  endblock head %}

{% block content %}
<h2 class="L">Подписки</h2>
{% for one in podpiska %}
<h3 class="main">{{ one.name }}</h3>
    <div class="cont">
    {% for kino in one.kino_set.all%}
        <div class="card">
        <img src="{% static kino.image %}" alt="">
            <h4>{{ kino.title }}</h4>
            <h4>{{ kino.genre }}</h4>
        {% if not user.username %}
            <a href="{% url 'prosmotr' kino.id one.id 0 %}">
            <button>Смотреть</button>
        </a>
        {% else %}
         <a href="{% url 'prosmotr' kino.id one.id user.id %}">
            <button>Смотреть</button>
        </a>
        {% endif %}
        </div>
        {% endfor %}
        </div>


    {% endfor %}


{% endblock content %}

templates/prosmotr.html
{% extends 'index.html' %}
{% load static %}
{% block head %}

    <title>Просмотр</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/prosmotr.css' %}">
    {%  endblock head %}
{% block content %}

<h3>Фильм {{ kino }}</h3>
    <div class="screen">
    {% if prava %}
    <h4>Приятного просмотра</h4>
    {% else %}
    <h4>Купить подписку</h4>
    {% endif %}



    </div>
    <h3>Ваша подписка {{ status }}</h3>
    <h3>для фильма {{ statuskino }}</h3>

    {% if not prava %}
        {% if user.username %}
        <h4>
    <a href="{% url 'buystatus' type=2 %}">Купить базовую</a>
    </h4>

    <h4>
    <a href="{% url 'buystatus' type=3 %}">Купить супер</a>
    </h4>
        {% else %}
       <h4>
    <a href="{% url 'login'  %}">Купить базовую</a>
    </h4>

    <h4>
    <a href="{% url 'login'  %}">Купить супер</a>
        {% endif %}


    {% endif %}

{% endblock %}